language: ruby
gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_2.gemfile
  - Gemfile
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0

env:
  matrix:
    - MONGODB=3.4
    - MONGODB=3.6

before_script:
  - docker run -d -p 27017:27017 mongo:${MONGODB}
  - docker ps -a

notifications:
  email: false
bundler_args: --without development
matrix:
  exclude:
    - rvm: 2.6.5
      gemfile: gemfiles/rails4_2.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails4_2.gemfile
