language: ruby
gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_2.gemfile
  - Gemfile
rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
notifications:
  email: false
bundler_args: --without development
services: mongodb
matrix:
  include:
    - rvm: 2.6.5
      gemfile: Gemfile
  exclude:
    - rvm: 2.6.5
      gemfile: gemfiles/rails4_2.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails4_2.gemfile
