name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ruby-version:
        - jruby
        - 2.4.10
        - 2.5.8
        - 2.6.6
        - 2.7.1
        - 2.7.2
        gemfile:
        - gemfiles/rails5_0.gemfile
        - gemfiles/rails5_1.gemfile
        - gemfiles/rails5_2.gemfile
        - gemfiles/rails6_0.gemfile
        - gemfiles/rails6_1.gemfile
        experimental:
        - false
        exclude:
          - ruby-version: 2.4.10
            gemfile: gemfiles/rails6_0.gemfile
            experimental: false
          - ruby-version: 2.4.10
            gemfile: gemfiles/rails6_1.gemfile
            experimental: false
        include:
          - ruby-version: 3.0.0-preview2
            gemfile: gemfiles/rails5_0.gemfile
            experimental: true
          - ruby-version: 3.0.0-preview2
            gemfile: gemfiles/rails5_1.gemfile
            experimental: true
          - ruby-version: 3.0.0-preview2
            gemfile: gemfiles/rails5_2.gemfile
            experimental: true
          - ruby-version: 3.0.0-preview2
            gemfile: gemfiles/rails6_0.gemfile
            experimental: true
          - ruby-version: 3.0.0-preview2
            gemfile: gemfiles/rails6_1.gemfile
            experimental: true
          - ruby-version: head
            gemfile: gemfiles/rails5_0.gemfile
            experimental: true
          - ruby-version: head
            gemfile: gemfiles/rails5_1.gemfile
            experimental: true
          - ruby-version: head
            gemfile: gemfiles/rails5_2.gemfile
            experimental: true
          - ruby-version: head
            gemfile: gemfiles/rails6_0.gemfile
            experimental: true
          - ruby-version: head
            gemfile: gemfiles/rails6_1.gemfile
            experimental: true
    env:
      JRUBY_OPTS: "--1.9"
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4
    - name: Install dependencies
      run: "bundle install --without development"
    - name: Run tests
      run: "bundle exec rake"
