name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - jruby
          - 2.4.10
          - 2.5.9
          - 2.6.10
          - 2.7.6
          - 3.0.4
        gemfile:
          - gemfiles/rails5_0.gemfile
          - gemfiles/rails5_1.gemfile
          - gemfiles/rails5_2.gemfile
          - gemfiles/rails6_0.gemfile
          - gemfiles/rails6_1.gemfile
          - gemfiles/rails7_0.gemfile
        exclude:
          - ruby-version: jruby
            gemfile: gemfiles/rails7_0.gemfile
          - ruby-version: 2.4.10
            gemfile: gemfiles/rails7_0.gemfile
          - ruby-version: 2.4.10
            gemfile: gemfiles/rails6_0.gemfile
          - ruby-version: 2.4.10
            gemfile: gemfiles/rails6_1.gemfile
          - ruby-version: 2.5.9
            gemfile: gemfiles/rails7_0.gemfile
          - ruby-version: 2.6.10
            gemfile: gemfiles/rails7_0.gemfile
          - ruby-version: 3.0.4
            gemfile: gemfiles/rails5_0.gemfile
          - ruby-version: 3.0.4
            gemfile: gemfiles/rails5_1.gemfile
          - ruby-version: 3.0.4
            gemfile: gemfiles/rails5_2.gemfile
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
    env:
      JRUBY_OPTS: "--1.9"
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
    - name: Install dependencies
      run: "bundle install --without development"
    - name: Run tests
      run: "bundle exec rake"
